# Generated by Django 5.0.7 on 2026-07-27 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("printers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("user", "User"), ("department", "Department")],
                        max_length=16,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("daily", "Daily"), ("monthly", "Monthly")],
                        max_length=16,
                    ),
                ),
                ("page_limit", models.PositiveIntegerField(default=0)),
                (
                    "cost_limit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("active_from", models.DateField()),
                ("active_until", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota_rules",
                        to="printers.department",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuotaUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("pages_used", models.PositiveIntegerField(default=0)),
                (
                    "cost_used",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_start"],
            },
        ),
        migrations.AddConstraint(
            model_name="quotarule",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("scope", "user"), ("user__isnull", False)),
                    models.Q(("department__isnull", False), ("scope", "department")),
                    _connector="OR",
                ),
                name="quota_rule_must_have_target",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quotausage",
            unique_together={("user", "period_start")},
        ),
    ]
