"""Quotas domain interfaces."""
from __future__ import annotations

from typing import Optional, Protocol

from .records import QuotaRuleRecord, QuotaUsageRecord


class IQuotaRuleRepository(Protocol):
    def list_for_user(self, user_id: int) -> list[QuotaRuleRecord]: ...
    def list_all(self) -> list[QuotaRuleRecord]: ...
    def create(self, data: dict) -> QuotaRuleRecord: ...
    def update(self, rule_id: int, data: dict) -> Optional[QuotaRuleRecord]: ...
    def delete(self, rule_id: int) -> bool: ...


class IQuotaUsageRepository(Protocol):
    def get(self, user_id: int, period_start: str) -> Optional[QuotaUsageRecord]: ...
    def save(self, user_id: int, period_start: str, period_end: str,
             pages_used: int, cost_used) -> QuotaUsageRecord: ...
    def list_for_user(self, user_id: int) -> list[QuotaUsageRecord]: ...