"""Printers domain interfaces."""
from __future__ import annotations

from typing import Optional, Protocol

from .records import DepartmentRecord, PrinterRecord


class IPrinterRepository(Protocol):
    def get_by_name(self, name: str) -> Optional[PrinterRecord]: ...
    def get_by_id(self, printer_id: int) -> Optional[PrinterRecord]: ...
    def list_all(self) -> list[PrinterRecord]: ...
    def create(self, data: dict) -> PrinterRecord: ...
    def update(self, printer_id: int, data: dict) -> Optional[PrinterRecord]: ...
    def delete(self, printer_id: int) -> bool: ...


class IDepartmentRepository(Protocol):
    def get_by_id(self, department_id: int) -> Optional[DepartmentRecord]: ...
    def list_all(self) -> list[DepartmentRecord]: ...
    def create(self, name: str, description: str = "") -> DepartmentRecord: ...
    def update(self, department_id: int, name: str, description: str) -> Optional[DepartmentRecord]: ...
    def delete(self, department_id: int) -> bool: ...