# Generated by Django 5.0.7 on 2026-07-27 06:38

import apps.accounts.infrastructure.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.infrastructure.models.UserManager()),
            ],
        ),
    ]
