# Generated by Django 5.0.7 on 2026-07-27 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("printers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, editable=False, unique=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("print", "Print"),
                            ("scan", "Scan"),
                            ("copy", "Copy"),
                        ],
                        default="print",
                        max_length=8,
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("printer_name", models.CharField(blank=True, max_length=128)),
                ("document_name", models.CharField(blank=True, max_length=255)),
                ("pages", models.PositiveIntegerField(default=0)),
                ("copies", models.PositiveIntegerField(default=1)),
                ("color", models.BooleanField(default=False)),
                ("duplex", models.BooleanField(default=False)),
                ("submitted_at", models.DateTimeField()),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("cups", "CUPS filter"),
                            ("windows", "Windows agent"),
                            ("api", "Developer API"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("flags", models.JSONField(blank=True, default=list)),
                (
                    "printer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="printers.printer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-captured_at"],
                "indexes": [
                    models.Index(
                        fields=["-captured_at"], name="jobs_printj_capture_24e3f9_idx"
                    ),
                    models.Index(
                        fields=["job_type"], name="jobs_printj_job_typ_1a0fe9_idx"
                    ),
                    models.Index(
                        fields=["source"], name="jobs_printj_source_fd9172_idx"
                    ),
                    models.Index(
                        fields=["user"], name="jobs_printj_user_id_a0bc26_idx"
                    ),
                    models.Index(
                        fields=["printer"], name="jobs_printj_printer_e02f7c_idx"
                    ),
                ],
            },
        ),
    ]
