"""Accounts domain interfaces (Protocols)."""
from __future__ import annotations

from typing import Optional, Protocol

from .records import DeveloperTokenRecord, DeveloperTokenSecret, TokenPair, UserRecord


class IUserRepository(Protocol):
    def get_by_email(self, email: str) -> Optional[UserRecord]: ...
    def get_by_id(self, user_id: int) -> Optional[UserRecord]: ...
    def verify_password(self, user_id: int, password: str) -> bool: ...


class IDeveloperTokenRepository(Protocol):
    def create(self, user_id: int, name: str, scopes: list) -> DeveloperTokenSecret: ...
    def list_for_user(self, user_id: int) -> list[DeveloperTokenRecord]: ...
    def revoke(self, token_id: int) -> None: ...
    def get_by_jti(self, jti: str) -> Optional[DeveloperTokenRecord]: ...


class ITokenService(Protocol):
    def issue_pair(self, user: UserRecord) -> TokenPair: ...
    def issue_developer_token(self, user_id: int, name: str, scopes: list) -> DeveloperTokenSecret: ...
    def verify(self, token: str) -> Optional[dict]: ...